pipeline {
  agent any
  
  stages {
    stage('Echo fatch'){
      steps {
        echo 'Git fatch'
        git url: 'https://github.com/Lockmen/spring-petclinic.git/',
          branch: main, credentialsId: 'gitCredential'
        
    }
  }
    

  stage('Maven Build'){
    steps {
        echo 'Maven Build'
    }
  }
   
  stages {
    stage('Docker Image'){
      steps {
        echo 'Docker Image!!'
    }
  }
    
    
 stages {
    stage('Image push'){
      steps {
        echo 'Image push!!'
    }
  }
  stages {
    stage('Codedeploy'){
      steps {
        echo 'Codedeploy!!'
    }
  }
    
 }


